# Generated by Django 4.2.5 on 2023-10-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
    ]
